/* This file is generated by Ziggy. */
export module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "partnerships.create": [],
    "partnerships.store": [],
    "job-postings.create": [],
    "job-postings.store": [],
    "info-lowongan.index": [],
    "info-lowongan.show": [
        {
            "name": "jobPosting",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "login.store": [],
    "admin.logout": [],
    "admin.dashboard": [],
    "admin.vission-misssions.index": [],
    "admin.vission-misssions.create": [],
    "admin.vission-misssions.store": [],
    "admin.vission-misssions.edit": [
        {
            "name": "visi_misi",
            "required": true
        }
    ],
    "admin.vission-misssions.update": [
        {
            "name": "visi_misi",
            "required": true
        }
    ],
    "admin.vission-misssions.destroy": [
        {
            "name": "visi_misi",
            "required": true
        }
    ],
    "admin.organizational-structures.index": [],
    "admin.organizational-structures.create": [],
    "admin.organizational-structures.store": [],
    "admin.organizational-structures.edit": [
        {
            "name": "struktur_organisasi",
            "required": true
        }
    ],
    "admin.organizational-structures.update": [
        {
            "name": "struktur_organisasi",
            "required": true
        }
    ],
    "admin.organizational-structures.destroy": [
        {
            "name": "struktur_organisasi",
            "required": true
        }
    ],
    "admin.histories.index": [],
    "admin.histories.create": [],
    "admin.histories.store": [],
    "admin.histories.edit": [
        {
            "name": "sejarah",
            "required": true
        }
    ],
    "admin.histories.update": [
        {
            "name": "sejarah",
            "required": true
        }
    ],
    "admin.histories.destroy": [
        {
            "name": "sejarah",
            "required": true
        }
    ],
    "admin.posts.index": [],
    "admin.posts.create": [],
    "admin.posts.store": [],
    "admin.posts.edit": [
        {
            "name": "postingan",
            "required": true
        }
    ],
    "admin.posts.update": [
        {
            "name": "postingan",
            "required": true
        }
    ],
    "admin.posts.destroy": [
        {
            "name": "postingan",
            "required": true
        }
    ],
    "admin.majors.index": [],
    "admin.majors.create": [],
    "admin.majors.store": [],
    "admin.majors.edit": [
        {
            "name": "jurusan",
            "required": true
        }
    ],
    "admin.majors.update": [
        {
            "name": "jurusan",
            "required": true
        }
    ],
    "admin.majors.destroy": [
        {
            "name": "jurusan",
            "required": true
        }
    ],
    "admin.works.index": [],
    "admin.works.create": [],
    "admin.works.store": [],
    "admin.works.edit": [
        {
            "name": "karya",
            "required": true
        }
    ],
    "admin.works.update": [
        {
            "name": "karya",
            "required": true
        }
    ],
    "admin.works.destroy": [
        {
            "name": "karya",
            "required": true
        }
    ],
    "admin.contacts.index": [],
    "admin.contacts.create": [],
    "admin.contacts.store": [],
    "admin.contacts.edit": [
        {
            "name": "kontak",
            "required": true
        }
    ],
    "admin.contacts.update": [
        {
            "name": "kontak",
            "required": true
        }
    ],
    "admin.contacts.destroy": [
        {
            "name": "kontak",
            "required": true
        }
    ],
    "admin.messages.index": [],
    "admin.messages.store": [],
    "admin.messages.show": [
        {
            "name": "pesan",
            "required": true
        }
    ],
    "admin.messages.edit": [
        {
            "name": "pesan",
            "required": true
        }
    ],
    "admin.messages.update": [
        {
            "name": "pesan",
            "required": true
        }
    ],
    "admin.messages.destroy": [
        {
            "name": "pesan",
            "required": true
        }
    ],
    "admin.partnerships.index": [],
    "admin.partnerships.show": [
        {
            "name": "partnership",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.partnerships.approve": [
        {
            "name": "partnership",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.partnerships.reject": [
        {
            "name": "partnership",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.job-postings.index": [],
    "admin.job-postings.show": [
        {
            "name": "jobPosting",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.job-postings.approve": [
        {
            "name": "jobPosting",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.job-postings.reject": [
        {
            "name": "jobPosting",
            "required": true,
            "binding": "id"
        }
    ],
    "company.dashboard": [],
    "company.profile.edit": [],
    "company.profile.update": [],
    "company.job-postings.index": [],
    "company.job-postings.create": [],
    "company.job-postings.store": [],
    "company.job-postings.edit": [
        {
            "name": "jobPosting",
            "required": true,
            "binding": "id"
        }
    ],
    "company.job-postings.update": [
        {
            "name": "jobPosting",
            "required": true,
            "binding": "id"
        }
    ],
    "company.job-postings.toggle": [
        {
            "name": "jobPosting",
            "required": true,
            "binding": "id"
        }
    ],
    "company.job-postings.destroy": [
        {
            "name": "jobPosting",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance.edit": [],
    "register": [],
    "register.store": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirm.store": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}

declare global {
  function route(name: string, params?: Record<string, any>, absolute?: boolean): string;
}

export {};
