/* This file is generated by Ziggy. */
export module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "dashboard": [],
    "visi-misi.index": [],
    "visi-misi.create": [],
    "visi-misi.store": [],
    "visi-misi.edit": [
        {
            "name": "visi_misi",
            "required": true
        }
    ],
    "visi-misi.update": [
        {
            "name": "visi_misi",
            "required": true
        }
    ],
    "visi-misi.destroy": [
        {
            "name": "visi_misi",
            "required": true
        }
    ],
    "struktur-organisasi.index": [],
    "struktur-organisasi.create": [],
    "struktur-organisasi.store": [],
    "struktur-organisasi.edit": [
        {
            "name": "struktur_organisasi",
            "required": true
        }
    ],
    "struktur-organisasi.update": [
        {
            "name": "struktur_organisasi",
            "required": true
        }
    ],
    "struktur-organisasi.destroy": [
        {
            "name": "struktur_organisasi",
            "required": true
        }
    ],
    "sejarah.index": [],
    "sejarah.create": [],
    "sejarah.store": [],
    "sejarah.edit": [
        {
            "name": "sejarah",
            "required": true
        }
    ],
    "sejarah.update": [
        {
            "name": "sejarah",
            "required": true
        }
    ],
    "sejarah.destroy": [
        {
            "name": "sejarah",
            "required": true
        }
    ],
    "postingan.index": [],
    "postingan.create": [],
    "postingan.store": [],
    "postingan.edit": [
        {
            "name": "postingan",
            "required": true
        }
    ],
    "postingan.update": [
        {
            "name": "postingan",
            "required": true
        }
    ],
    "postingan.destroy": [
        {
            "name": "postingan",
            "required": true
        }
    ],
    "jurusan.index": [],
    "jurusan.create": [],
    "jurusan.store": [],
    "jurusan.edit": [
        {
            "name": "jurusan",
            "required": true
        }
    ],
    "jurusan.update": [
        {
            "name": "jurusan",
            "required": true
        }
    ],
    "jurusan.destroy": [
        {
            "name": "jurusan",
            "required": true
        }
    ],
    "karya.index": [],
    "karya.create": [],
    "karya.store": [],
    "karya.edit": [
        {
            "name": "karya",
            "required": true
        }
    ],
    "karya.update": [
        {
            "name": "karya",
            "required": true
        }
    ],
    "karya.destroy": [
        {
            "name": "karya",
            "required": true
        }
    ],
    "kontak.index": [],
    "kontak.create": [],
    "kontak.store": [],
    "kontak.edit": [
        {
            "name": "kontak",
            "required": true
        }
    ],
    "kontak.update": [
        {
            "name": "kontak",
            "required": true
        }
    ],
    "kontak.destroy": [
        {
            "name": "kontak",
            "required": true
        }
    ],
    "pesan.index": [],
    "pesan.show": [
        {
            "name": "inquiry",
            "required": true,
            "binding": "id"
        }
    ],
    "pesan.update": [
        {
            "name": "inquiry",
            "required": true,
            "binding": "id"
        }
    ],
    "pesan.destroy": [
        {
            "name": "inquiry",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance.edit": [],
    "register": [],
    "register.store": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirm.store": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}

declare global {
  function route(name: string, params?: Record<string, any>, absolute?: boolean): string;
}

export {};
